#!/usr/bin/env python3
"""Writes card_classes.h: one byte per card ID (1-722) for card_frame_colors.c.

  bits 0-1  the card's frame in the TCG: 0 Normal, 1 Effect (and Flip),
            2 Fusion, 3 Ritual; 0 for anything that is not a monster
  bit 4     the result of some fusion in the game's own table
  bit 5     the result of one of the game's rituals

The TCG frame comes from YGOPRODeck's card database, matched by password
(the game's passwords are the TCG's) and then by name. Fetch it first:

  curl -o cardinfo.json https://db.ygoprodeck.com/api/v7/cardinfo.php
  python3 mods/card-frame-colors/gen_card_classes.py cardinfo.json ritual.json

ritual.json is sg4e/YGOFM-gamedata's sqlite/json/ritualinfo.json. The
fusion results are this repository's notes/research tables."""
import csv, json, os, re, sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
FRAMES = {"normal": 0, "effect": 1, "fusion": 2, "ritual": 3}
# The game's spelling differs from the TCG's too much for either match.
BY_HAND = {"Meteor B. Dragon": 2, "Psycho-Puppet": 1}


def key(name):
    return re.sub(r"[^a-z0-9]", "", name.lower())


def main(cardinfo, ritualinfo):
    by_password, by_name = {}, {}
    for card in json.load(open(cardinfo))["data"]:
        frame = FRAMES.get(card.get("frameType", "").split("_")[0])
        if frame is None:
            continue
        by_name.setdefault(key(card["name"]), frame)
        for image in card.get("card_images", []) + [{"id": card["id"]}]:
            by_password[int(image["id"])] = frame

    classes, missing = [0] * 723, []
    with open(os.path.join(ROOT, "notes/card-catalog.csv")) as f:
        for row in csv.DictReader(f):
            cid = int(row["id"])
            if row["type"] in ("Magic", "Trap", "Ritual", "Equip"):
                continue
            password = int(row["password"]) if row["password"].isdigit() else None
            frame = by_password.get(password)
            if frame is None:
                frame = by_name.get(key(row["name"]), BY_HAND.get(row["name"]))
            if frame is None:
                missing.append(row["name"])
                frame = 0
            classes[cid] = frame

    with open(os.path.join(ROOT, "notes/research/fusion-and-drop-tables/fusions_by_result.csv")) as f:
        for row in csv.DictReader(f):
            classes[int(row["result_id"])] |= 0x10
    for ritual in json.load(open(ritualinfo)):
        classes[int(ritual["result"])] |= 0x20

    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "card_classes.h")
    with open(out, "w") as f:
        f.write("/* Generated by gen_card_classes.py; see there for the bits. */\n")
        f.write("static const unsigned char card_classes[723] = {\n")
        for i in range(0, 723, 16):
            f.write("    " + ", ".join("0x%02X" % c for c in classes[i:i + 16]) + ",\n")
        f.write("};\n")
    counts = [sum(1 for c in classes[1:] if c & 3 == n) for n in range(4)]
    print("normal/effect/fusion/ritual:", counts, "fm fusion results:",
          sum(1 for c in classes if c & 0x10), "fm ritual results:", sum(1 for c in classes if c & 0x20))
    if missing:
        print("not found, left Normal:", ", ".join(missing))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
